---
- name: Configurar script do agente de inventário
  hosts: all
  become: yes
  tasks:
    - name: Copiar o script para /usr/local/bin/
      copy:
        src: utf-inventory-agent.py
        dest: /usr/local/bin/utf-inventory-agent.py
        mode: '0755'

    - name: Criar script em /etc/profile.d/ para executar no login
      copy:
        content: |
          #!/bin/bash
          python3 /usr/local/bin/utf-inventory-agent.py
        dest: /etc/profile.d/utf-inventory-agent.sh
        mode: '0755'
