---
- name: Configurar serviço de renomeação de hostname
  hosts: all
  become: yes  # Executa tarefas como root
  tasks:
    - name: Copiar o script para /usr/local/bin/
      copy:
        src: utf-change-hostname-from-dns.py  # Caminho local do script
        dest: /usr/local/bin/utf-change-hostname-from-dns.py
        mode: '0755'  # Permissões para o script

    - name: Criar arquivo de serviço do systemd
      copy:
        content: |
          [Unit]
          Description=Script para renomear o hostname baseado em IP
          After=network.target

          [Service]
          ExecStart=/usr/bin/python3 /usr/local/bin/utf-change-hostname-from-dns.py
          User=root
          Type=simple
          Restart=on-failure

          [Install]
          WantedBy=multi-user.target
        dest: /etc/systemd/system/rename-hostname.service
        mode: '0644'  # Permissões para o arquivo de serviço

    - name: Recarregar systemd para reconhecer o novo serviço
      systemd:
        daemon_reload: yes

    - name: Habilitar e iniciar o serviço
      systemd:
        name: rename-hostname.service
        enabled: yes
        state: started
