"""Make patrimony column nullable

Revision ID: ae9a9494ea98
Revises: 
Create Date: 2024-08-07 13:31:27.424433

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ae9a9494ea98'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('system_info', schema=None) as batch_op:
        batch_op.add_column(sa.Column('patrimony', sa.String(length=50), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('system_info', schema=None) as batch_op:
        batch_op.drop_column('patrimony')

    # ### end Alembic commands ###
